// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../mocks/client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "agreements-generator/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeneratorClient is a mock of GeneratorClient interface.
type MockGeneratorClient struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorClientMockRecorder
	isgomock struct{}
}

// MockGeneratorClientMockRecorder is the mock recorder for MockGeneratorClient.
type MockGeneratorClientMockRecorder struct {
	mock *MockGeneratorClient
}

// NewMockGeneratorClient creates a new mock instance.
func NewMockGeneratorClient(ctrl *gomock.Controller) *MockGeneratorClient {
	mock := &MockGeneratorClient{ctrl: ctrl}
	mock.recorder = &MockGeneratorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratorClient) EXPECT() *MockGeneratorClientMockRecorder {
	return m.recorder
}

// BulkGenerate mocks base method.
func (m *MockGeneratorClient) BulkGenerate(ctx context.Context, archive []byte, responseChan chan *domain.GenResponse, errChan chan error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BulkGenerate", ctx, archive, responseChan, errChan)
}

// BulkGenerate indicates an expected call of BulkGenerate.
func (mr *MockGeneratorClientMockRecorder) BulkGenerate(ctx, archive, responseChan, errChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkGenerate", reflect.TypeOf((*MockGeneratorClient)(nil).BulkGenerate), ctx, archive, responseChan, errChan)
}

// Close mocks base method.
func (m *MockGeneratorClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockGeneratorClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGeneratorClient)(nil).Close))
}
