// Code generated by MockGen. DO NOT EDIT.
// Source: generator.go
//
// Generated by this command:
//
//	mockgen -source=generator.go -destination=../mocks/generator.go -package=mocks -mock_names=Generator=MockGeneratorService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "agreements-generator/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeneratorService is a mock of Generator interface.
type MockGeneratorService struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorServiceMockRecorder
	isgomock struct{}
}

// MockGeneratorServiceMockRecorder is the mock recorder for MockGeneratorService.
type MockGeneratorServiceMockRecorder struct {
	mock *MockGeneratorService
}

// NewMockGeneratorService creates a new mock instance.
func NewMockGeneratorService(ctrl *gomock.Controller) *MockGeneratorService {
	mock := &MockGeneratorService{ctrl: ctrl}
	mock.recorder = &MockGeneratorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratorService) EXPECT() *MockGeneratorServiceMockRecorder {
	return m.recorder
}

// BulkGenerate mocks base method.
func (m *MockGeneratorService) BulkGenerate(ctx context.Context, archiveBytes []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkGenerate", ctx, archiveBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkGenerate indicates an expected call of BulkGenerate.
func (mr *MockGeneratorServiceMockRecorder) BulkGenerate(ctx, archiveBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkGenerate", reflect.TypeOf((*MockGeneratorService)(nil).BulkGenerate), ctx, archiveBytes)
}

// CheckJobStatus mocks base method.
func (m *MockGeneratorService) CheckJobStatus(ctx context.Context, id string) (domain.JobStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckJobStatus", ctx, id)
	ret0, _ := ret[0].(domain.JobStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckJobStatus indicates an expected call of CheckJobStatus.
func (mr *MockGeneratorServiceMockRecorder) CheckJobStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckJobStatus", reflect.TypeOf((*MockGeneratorService)(nil).CheckJobStatus), ctx, id)
}

// GetArchive mocks base method.
func (m *MockGeneratorService) GetArchive(ctx context.Context, jobID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchive", ctx, jobID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArchive indicates an expected call of GetArchive.
func (mr *MockGeneratorServiceMockRecorder) GetArchive(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchive", reflect.TypeOf((*MockGeneratorService)(nil).GetArchive), ctx, jobID)
}

// GetArchiveInfo mocks base method.
func (m *MockGeneratorService) GetArchiveInfo(ctx context.Context, jobID string) ([]domain.FilesErrors, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveInfo", ctx, jobID)
	ret0, _ := ret[0].([]domain.FilesErrors)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArchiveInfo indicates an expected call of GetArchiveInfo.
func (mr *MockGeneratorServiceMockRecorder) GetArchiveInfo(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveInfo", reflect.TypeOf((*MockGeneratorService)(nil).GetArchiveInfo), ctx, jobID)
}
