// Code generated by MockGen. DO NOT EDIT.
// Source: client_test.go
//
// Generated by this command:
//
//	mockgen -source=client_test.go -destination=../mocks/grpcClient.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	generator "agreements-generator/gen/go/generator"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockGeneratorClientNoOp is a mock of GeneratorClientNoOp interface.
type MockGeneratorClientNoOp struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorClientNoOpMockRecorder
	isgomock struct{}
}

// MockGeneratorClientNoOpMockRecorder is the mock recorder for MockGeneratorClientNoOp.
type MockGeneratorClientNoOpMockRecorder struct {
	mock *MockGeneratorClientNoOp
}

// NewMockGeneratorClientNoOp creates a new mock instance.
func NewMockGeneratorClientNoOp(ctrl *gomock.Controller) *MockGeneratorClientNoOp {
	mock := &MockGeneratorClientNoOp{ctrl: ctrl}
	mock.recorder = &MockGeneratorClientNoOpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratorClientNoOp) EXPECT() *MockGeneratorClientNoOpMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockGeneratorClientNoOp) Generate(ctx context.Context, in *generator.GenerateRequest, opts ...grpc.CallOption) (*generator.GenerateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Generate", varargs...)
	ret0, _ := ret[0].(*generator.GenerateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGeneratorClientNoOpMockRecorder) Generate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGeneratorClientNoOp)(nil).Generate), varargs...)
}
