// Code generated by MockGen. DO NOT EDIT.
// Source: redis.go
//
// Generated by this command:
//
//	mockgen -source=redis.go -destination=../mocks/redis.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacher is a mock of Cacher interface.
type MockCacher struct {
	ctrl     *gomock.Controller
	recorder *MockCacherMockRecorder
	isgomock struct{}
}

// MockCacherMockRecorder is the mock recorder for MockCacher.
type MockCacherMockRecorder struct {
	mock *MockCacher
}

// NewMockCacher creates a new mock instance.
func NewMockCacher(ctrl *gomock.Controller) *MockCacher {
	mock := &MockCacher{ctrl: ctrl}
	mock.recorder = &MockCacherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacher) EXPECT() *MockCacherMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacher) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacher)(nil).Close))
}

// DeleteJobStatus mocks base method.
func (m *MockCacher) DeleteJobStatus(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobStatus", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJobStatus indicates an expected call of DeleteJobStatus.
func (mr *MockCacherMockRecorder) DeleteJobStatus(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobStatus", reflect.TypeOf((*MockCacher)(nil).DeleteJobStatus), ctx, jobID)
}

// GetJobStatus mocks base method.
func (m *MockCacher) GetJobStatus(ctx context.Context, jobID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", ctx, jobID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockCacherMockRecorder) GetJobStatus(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockCacher)(nil).GetJobStatus), ctx, jobID)
}

// SetJobStatus mocks base method.
func (m *MockCacher) SetJobStatus(ctx context.Context, jobID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJobStatus", ctx, jobID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJobStatus indicates an expected call of SetJobStatus.
func (mr *MockCacherMockRecorder) SetJobStatus(ctx, jobID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobStatus", reflect.TypeOf((*MockCacher)(nil).SetJobStatus), ctx, jobID, status)
}
