// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=../mocks/storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "agreements-generator/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeneratorStorage is a mock of GeneratorStorage interface.
type MockGeneratorStorage struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorStorageMockRecorder
	isgomock struct{}
}

// MockGeneratorStorageMockRecorder is the mock recorder for MockGeneratorStorage.
type MockGeneratorStorageMockRecorder struct {
	mock *MockGeneratorStorage
}

// NewMockGeneratorStorage creates a new mock instance.
func NewMockGeneratorStorage(ctrl *gomock.Controller) *MockGeneratorStorage {
	mock := &MockGeneratorStorage{ctrl: ctrl}
	mock.recorder = &MockGeneratorStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratorStorage) EXPECT() *MockGeneratorStorageMockRecorder {
	return m.recorder
}

// CheckJobStatus mocks base method.
func (m *MockGeneratorStorage) CheckJobStatus(ctx context.Context, id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckJobStatus", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckJobStatus indicates an expected call of CheckJobStatus.
func (mr *MockGeneratorStorageMockRecorder) CheckJobStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckJobStatus", reflect.TypeOf((*MockGeneratorStorage)(nil).CheckJobStatus), ctx, id)
}

// GetArchive mocks base method.
func (m *MockGeneratorStorage) GetArchive(ctx context.Context, jobID string) (string, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchive", ctx, jobID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArchive indicates an expected call of GetArchive.
func (mr *MockGeneratorStorageMockRecorder) GetArchive(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchive", reflect.TypeOf((*MockGeneratorStorage)(nil).GetArchive), ctx, jobID)
}

// GetArchiveInfo mocks base method.
func (m *MockGeneratorStorage) GetArchiveInfo(ctx context.Context, jobID string) (string, []domain.FilesErrors, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveInfo", ctx, jobID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]domain.FilesErrors)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetArchiveInfo indicates an expected call of GetArchiveInfo.
func (mr *MockGeneratorStorageMockRecorder) GetArchiveInfo(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveInfo", reflect.TypeOf((*MockGeneratorStorage)(nil).GetArchiveInfo), ctx, jobID)
}

// SaveResponse mocks base method.
func (m *MockGeneratorStorage) SaveResponse(ctx context.Context, job domain.Job, response *domain.GenResponse, err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResponse", ctx, job, response, err)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveResponse indicates an expected call of SaveResponse.
func (mr *MockGeneratorStorageMockRecorder) SaveResponse(ctx, job, response, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResponse", reflect.TypeOf((*MockGeneratorStorage)(nil).SaveResponse), ctx, job, response, err)
}

// StoreJob mocks base method.
func (m *MockGeneratorStorage) StoreJob(ctx context.Context, job domain.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreJob indicates an expected call of StoreJob.
func (mr *MockGeneratorStorageMockRecorder) StoreJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreJob", reflect.TypeOf((*MockGeneratorStorage)(nil).StoreJob), ctx, job)
}

// UpdateJob mocks base method.
func (m *MockGeneratorStorage) UpdateJob(ctx context.Context, job domain.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateJob indicates an expected call of UpdateJob.
func (mr *MockGeneratorStorageMockRecorder) UpdateJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJob", reflect.TypeOf((*MockGeneratorStorage)(nil).UpdateJob), ctx, job)
}

// MockUserStorage is a mock of UserStorage interface.
type MockUserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUserStorageMockRecorder
	isgomock struct{}
}

// MockUserStorageMockRecorder is the mock recorder for MockUserStorage.
type MockUserStorageMockRecorder struct {
	mock *MockUserStorage
}

// NewMockUserStorage creates a new mock instance.
func NewMockUserStorage(ctrl *gomock.Controller) *MockUserStorage {
	mock := &MockUserStorage{ctrl: ctrl}
	mock.recorder = &MockUserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStorage) EXPECT() *MockUserStorageMockRecorder {
	return m.recorder
}

// LogIn mocks base method.
func (m *MockUserStorage) LogIn(ctx context.Context, login string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogIn", ctx, login)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogIn indicates an expected call of LogIn.
func (mr *MockUserStorageMockRecorder) LogIn(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogIn", reflect.TypeOf((*MockUserStorage)(nil).LogIn), ctx, login)
}

// Register mocks base method.
func (m *MockUserStorage) Register(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockUserStorageMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserStorage)(nil).Register), ctx, user)
}
