services:
  worker:
    container_name: worker
    build: ./worker/
    ports:
      - "50051:50051"
  
  server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./config/local.yaml:/root/config.yaml
    depends_on:
      - worker
