syntax = "proto3";

package generator;

option go_package = "agreements-generator/proto/generator;generator";

service Generator {
  rpc Generate (GenerateRequest) returns (GenerateResponse);
}

message GenerateRequest {
  bytes archive = 1;
}

message GenerateResponse {
  bytes zip_archive = 1;
  repeated FileErrors errors = 2;
  int32 generated_count = 3;
}

message FileErrors {
  string file_name = 1;
  repeated FileError errors = 2;
}

message FileError {
  int32 code = 1;
  string message = 2;
}